DECLARE 
	@CLIENTE		VARCHAR(10),
	@DATA			VARCHAR(8),
	@FILIAL			VARCHAR(2),
	@NUMERO_PEDIDO	VARCHAR(6)

SET @CLIENTE		= '003848'
SET	@DATA			= '20220407'
SET @FILIAL			= '03'
SET @NUMERO_PEDIDO	= '144918'

--VERIFICA TITULOS VENCIDOS EM ABERTO
SELECT 
* 
FROM 
	SE1020 SE1 
WHERE 
	D_E_L_E_T_ <> '*' 
	AND E1_BAIXA  = ''       
	AND E1_VENCREA < @DATA
	AND E1_CLIENTE   =  @CLIENTE
	AND E1_TIPO <> 'RA'

--SALDO DE TITULOS EM ABERTO
SELECT SUM(E1_SALDO) VALAB  
FROM 
	SE1020 SE1  
WHERE 
	D_E_L_E_T_ <> '*' 
	AND E1_BAIXA  = ''       
	AND E1_CLIENTE   =  @CLIENTE
	AND E1_TIPO <> 'RA'

--SALDO DE PEDIDOS LIBERADOS
SELECT SUM(C6_VALOR) VALSL 
FROM 
	SC6020 SC6
INNER JOIN SC9020 SC9 ON SC9.D_E_L_E_T_ = '' 
	AND C9_FILIAL   = @FILIAL
	AND C9_PEDIDO  = C6_NUM 
	AND C9_ITEM   = C6_ITEM
	AND C9_SEQUEN = '01'					
	AND C9_BLCRED = '  '		
INNER JOIN SF4020
	ON SF4020.D_E_L_E_T_ <> '*'
	AND F4_FILIAL = C6_FILIAL
	AND F4_CODIGO = C6_TES
	AND F4_DUPLIC = 'S'			 			 
WHERE 
	SC6.D_E_L_E_T_ <> '*' 
	AND C6_NOTA = ''
	AND C6_BLQ <> 'R'		      
	AND C6_CLI   =  @CLIENTE 
	AND C6_NUM   <>  @NUMERO_PEDIDO 

--SALDO PEDIDO ATUAL
SELECT 
	SUM(C6_VALOR) VALSL 
FROM SC6020 SC6
INNER JOIN SF4020
	ON SF4020.D_E_L_E_T_ <> '*'
	AND F4_FILIAL = C6_FILIAL
	AND F4_CODIGO = C6_TES
	AND F4_DUPLIC = 'S'			 			 
WHERE 
	SC6.D_E_L_E_T_ <> '*' 
	AND C6_NOTA = ''    
	AND C6_CLI   =  @CLIENTE 
	AND C6_NUM   =  @NUMERO_PEDIDO 

