ALTER VIEW VW_ITEMS_COM_PROBLEMAS_NO_CAMPO_C9QPCLIB
AS

-- =============================================
-- Author:		Alcedir Junior, Antonio Freitas
-- Create date: 21/01/2022
-- Description:	View para listar problemas no campo customizado C9_QPCLIB
-- Alteração: Alcedir Junior
-- =============================================

SELECT 
	D3_OP
	,C9_PEDIDO
	,C9_ITEM
	,SUM(C9_QPCLIB)		[C9_QPCLIB]
	,SUM(D3_PCLIBER)	[D3_PCLIBER]
	,C6_QNTV
	,FORMAT
	(CONVERT(DATE, D3_EMISSAO), 'dd/MM/yyyy')					[DATA APONTAMENTO]
	,dbo.F_StatusPedidoVenda(C9_PEDIDO, C9_FILIAL)				[STATUS PEDIDO VENDA]
	,dbo.F_StatusItemPedidoVenda(C9_PEDIDO, C9_ITEM, C9_FILIAL) [STATUS ITEM PEDIDO DE VENDA]
FROM SC9020 SC9 WITH (NOLOCK)
INNER JOIN SD3020 SD3 WITH (NOLOCK) ON 
	D3_OP = CONCAT(C9_PEDIDO,C9_ITEM, '001') 
	AND SD3.D_E_L_E_T_ = '' 
	AND D3_TM = '012' 
	AND D3_EMISSAO > '20211001' 
	AND D3_ESTORNO = '' 
INNER JOIN SC6020 SC6 WITH (NOLOCK) ON 
	C6_NUM = C9_PEDIDO 
	AND C6_ITEM = C9_ITEM 
	AND SC6.D_E_L_E_T_ = '' 
	AND C6_PRCUNIT <> 'K' 
WHERE 
	SC9.D_E_L_E_T_ = '' 
	AND C9_QPCLIB = 0 
	AND C9_BLCRED <> '04' 
	AND dbo.F_StatusPedidoVenda(C9_PEDIDO, C9_FILIAL) NOT IN ('PEDIDO ENCERRADO - ELIMINADO RESÍDUO')
GROUP BY 
	D3_OP, 
	C9_PEDIDO, 
	C9_ITEM, 
	D3_EMISSAO, 
	C6_QNTV,
	C9_FILIAL

UNION

SELECT 
	D3_OP
	,C9_PEDIDO
	,C9_ITEM
	,SUM(C9_QPCLIB)		[C9_QPCLIB]
	,SUM(D3_PCLIBER)	[D3_PCLIBER]
	,C6_QNTV
	,FORMAT(CONVERT(DATE, D3_EMISSAO), 'dd/MM/yyyy')			[DATA APONTAMENTO]
	,dbo.F_StatusPedidoVenda(C9_PEDIDO, C9_FILIAL)				[STATUS PEDIDO VENDA]
	,dbo.F_StatusItemPedidoVenda(C9_PEDIDO, C9_ITEM, C9_FILIAL) [STATUS ITEM PEDIDO DE VENDA]
FROM SC9020 SC9 WITH (NOLOCK)
INNER JOIN SD3020 SD3 WITH (NOLOCK) ON 
	D3_PEDIDO = C9_PEDIDO 
	AND D3_ITEMPED = C9_ITEM 
	AND SD3.D_E_L_E_T_ = '' 
	AND D3_TM = '012' 
	AND D3_EMISSAO > '20211001' 
	AND D3_ESTORNO = '' 
INNER JOIN SC6020 SC6 WITH (NOLOCK) ON 
	C6_NUM = C9_PEDIDO 
	AND C6_ITEM = C9_ITEM 
	AND SC6.D_E_L_E_T_ = '' 
	AND C6_PRCUNIT <> 'K'
WHERE 
	SC9.D_E_L_E_T_ = '' 
	AND C9_QPCLIB = 0 
	AND C9_BLCRED <> '04' 
	AND dbo.F_StatusPedidoVenda(C9_PEDIDO, C9_FILIAL) NOT IN ('PEDIDO ENCERRADO - ELIMINADO RESÍDUO')
GROUP BY 
	D3_OP, 
	C9_PEDIDO, 
	C9_ITEM, 
	D3_EMISSAO, 
	C6_QNTV,
	C9_FILIAL

